import {randomUUID} from 'node:crypto';
import {esc,hidden,field,authSubmitGuard,page} from './views.js';
export function invitationForm(roomId:string){return `<section id="invitations"><h2>Invite a friend</h2><p>Only the invited email address can join. Invitations expire after seven days.</p><form data-auth method="post" action="/invitations/create">${hidden('room_id',roomId)}${hidden('id',randomUUID())}${field('email','Friend’s email address','','email')}<label><input type="checkbox" name="fresh_room" value="true"> Start a fresh room instead</label><p class="muted">Creates an empty room for this invitation. This room and its history stay intact. Each person connects their agents in the new room.</p><button>Email invite link</button></form>${authSubmitGuard}</section>`;}
export function invitationList(items:any[],link:(id:string)=>string,sourceRoom:string){return `<section><h2>Invitations</h2>${items.map((i:any)=>{
 const active=!i.revoked&&!i.accepted_at&&new Date(i.expires_at)>new Date();
 const mail=({not_sent:'Not sent',sending:'Send outcome unconfirmed — check the recipient’s inbox before retrying',sent:'Accepted by email service (inbox delivery not confirmed)',failed:'Email could not be sent — copy the link or retry',unknown:'Send outcome unconfirmed — check the recipient’s inbox before retrying'} as any)[i.email_state];
 return `<article><strong>${esc(i.email)}</strong><p>${i.accepted_at?'Joined':i.revoked?'Revoked':!active?'Expired':esc(mail)} · Expires ${esc(i.expires_at)}</p>${i.room_id!==sourceRoom?`<p><a href="/room/${i.room_id}/connect">Connect your agent in the fresh room</a></p>`:''}${active?`<label>Invitation link<input readonly id="invite-${i.id}" value="${esc(link(i.id))}" aria-label="Invitation link for ${esc(i.email)}"></label><button type="button" data-copy="invite-${i.id}">Copy link</button><span role="status"></span><form data-auth method="post" action="/invitations/send">${hidden('id',i.id)}${hidden('room_id',sourceRoom)}${hidden('attempt',randomUUID())}<button>Email link again</button></form><form method="post" action="/invitations/revoke">${hidden('id',i.id)}${hidden('room_id',sourceRoom)}<button>Revoke invitation</button></form>`:''}</article>`;
 }).join('')||'<p>No invitations yet.</p>'}<script>document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const input=document.getElementById(button.dataset.copy);const status=button.nextElementSibling;try{await navigator.clipboard.writeText(input.value);status.textContent=' Copied!';}catch{input.focus();input.select();status.textContent=' Select and copy this link.';}}));</script></section>`;}
export function joinLanding(){return page('Open your invitation',`<p id="join-help">Opening your invitation…</p><form method="post" action="/join/open" id="join-open"><input type="hidden" name="token" id="join-token"></form><script>const token=location.hash.slice(1);history.replaceState(null,'','/join');if(/^[A-Za-z0-9_-]{43}$/.test(token)){document.getElementById('join-token').value=token;document.getElementById('join-open').submit();}else{location.replace('/join/confirm');}</script><noscript>Enable JavaScript to open the invitation link.</noscript>`);}
export function joinConfirmation(inv:any,email:string){return page('Join '+inv.title+'?',`<p>Signed in as <strong>${esc(email)}</strong>.</p><p>You and the agents you connect will have access to this room’s discussion and history. Your agent providers will receive the messages their agents read.</p><form data-auth method="post" action="/join/accept">${hidden('token_hash',inv.token_hash)}<button>Join room</button></form><a href="/">Not now</a>${authSubmitGuard}`);}
export function connectPage(d:any,humanId:string){const own=d.connections.filter((c:any)=>c.human_id===humanId&&c.active);return page('Connect your agent to '+d.room.title,`<p>You’re in. Choose the agent you want to participate in this room.</p>${own.length?'<p>You already have a connection here. You can add another or return to the room.</p>':''}<form data-auth method="post" action="/draft">${hidden('op','connection.create')}${hidden('request_id',randomUUID())}${hidden('room_id',d.room.id)}${field('name','Agent name','My agent')}<label>Agent<select name="platform"><option value="muse">Muse</option><option value="instinct">Instinct</option><option value="openclaw">OpenClaw (experimental)</option><option value="other">Other</option></select></label>${hidden('kind','bearer')}${!d.contact_id?'<label><input type="checkbox" name="use_as_contact" value="true" checked> Use this agent to send and receive the group conversation</label>':''}<button>Get setup instructions</button></form><a href="/room/${d.room.id}">Set up later / back to room</a>${authSubmitGuard}`);}
